version: "3.8"
services:
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  ui:
    build:
      context: ./ui/
      dockerfile: ui.Dockerfile
    container_name: ui
    ports:
      - "3000:3000"
    restart: always

volumes:
  postgres:
